on:
  workflow_call:
    inputs:
      image-name:
        type: string
        required: false
      min-versions-to-keep:
        type: number
        required: false
        default: 10

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Clean up old app container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ env.image-name || env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
          package-type: container
          min-versions-to-keep: ${{ inputs.min-versions-to-keep }}
